# Minimal Mimir configuration for demo purposes
multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9098

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /tmp/mimir

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /tmp/mimir/blocks

compactor:
  data_dir: /tmp/mimir/compactor
