global:
  scrape_interval: 15s

scrape_configs:
  # Scrape Prometheus metrics
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape Node Exporter metrics
  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "tempo"
    static_configs:
      - targets: ["localhost:3200"]

  - job_name: "beyla"
    static_configs:
      - targets: ["localhost:8999"]

  - job_name: "mimir"
    static_configs:
      - targets: ["localhost:9009"]

  - job_name: "pyroscope"
    static_configs:
      - targets: ["localhost:4040"]
